[package]
categories = ["api-bindings", "web-programming"]
description = "Utilities for implementing Matrix server applications."
homepage = "https://ruma.dev/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-server-util"
readme = "README.md"
repository = "https://github.com/ruma/ruma"
version = "0.2.0"
edition = "2021"
rust-version = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
headers = "0.3"
ruma-common = { workspace = true }
tracing = { workspace = true }
yap = "0.11.0"

[dev-dependencies]
tracing-subscriber = "0.3.16"
