[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "A procedural macro used by the ruma-events crate."
documentation = "https://docs.rs/ruma-events-macros"
edition = "2018"
homepage = "https://github.com/ruma/ruma-events-macros"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-events-macros"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api-macros"
version = "0.21.3"

[dependencies]
syn = { version = "1.0.31", features = ["full"] }
quote = "1.0.7"
proc-macro2 = "1.0.18"
matches = "0.1.8"

[lib]
proc-macro = true

[dev-dependencies]
ruma-identifiers = { version = "=0.17.0-pre.1", path = "../ruma-identifiers" }
serde_json = "1.0.55"
js_int = { version = "0.1.7", features = ["serde"] }
serde = { version = "1.0.113", features = ["derive"] }
