comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
newline_style = "Unix"
style_edition = "2024"
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
