[default.extend-words]
# Remove this once base64 gets correctly ignored by typos
# Or if we're able to ignore certain lines.
NAX = "NAX"
Nd = "Nd"
Wya = "Wya"
# thead html tag is not a typo, upstream PR pending
thead = "thead"

# all of these are valid words, but should never appear in this repo
sing = "sign"
singed = "signed"
singing = "signing"
