[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A Matrix client library."
documentation = "https://docs.rs/ruma-client"
edition = "2018"
homepage = "https://github.com/ruma/ruma-client"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client"
version = "0.1.0"

[dependencies]
futures = "0.1.25"
http = "0.1.14"
hyper = "0.12.16"
ruma-api = "0.6.0"
ruma-client-api = "0.2.0"
ruma-identifiers = "0.11.0"
serde_json = "1.0.33"
serde_urlencoded = "0.5.4"
url = "1.7.2"

[dependencies.hyper-tls]
optional = true
version = "0.3.1"

[dependencies.native-tls]
optional = true
version = "0.2.2"

[dependencies.serde]
version = "1.0.87"
features = ["derive"]

[dev-dependencies]
ruma-events = "0.11.0"
tokio = "0.1"

[features]
default = ["tls"]
tls = ["hyper-tls", "native-tls"]
