[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A Matrix client library."
documentation = "https://docs.rs/ruma-client"
homepage = "https://github.com/ruma/ruma-client"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client"
version = "0.1.0"

[dependencies]
futures = "0.1.7"
ruma-identifiers = "0.6.0"
serde = "0.8.21"
serde_json = "0.8.4"
tokio-core = "0.1.3"
url = "1.2.4"

[dependencies.hyper]
branch = "tokio"
git = "https://github.com/hyperium/hyper"

[dependencies.ruma-client-api]
git = "https://github.com/ruma/ruma-client-api"
