[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A procedural macro for generating ruma-api Endpoints."
documentation = "https://docs.rs/ruma-api-macros"
homepage = "https://github.com/ruma/ruma-api-macros"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api-macros"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api-macros"
version = "0.1.0"

[dependencies]
quote = "0.5.2"
ruma-api = "0.5.0"

[dependencies.syn]
version = "0.13.4"
features = ["full"]

[dependencies.proc-macro2]
version = "0.3.8"
features = ["nightly"]

[dev-dependencies]
futures = "0.1.21"
http = "0.1.5"
serde = "1.0.45"
serde_derive = "1.0.45"
serde_json = "1.0.17"
serde_urlencoded = "0.5.1"
url = "1.7.0"

[lib]
proc-macro = true
