[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings"]
description = "Serializable types for the events in the Matrix specification."
documentation = "https://docs.rs/ruma-events"
homepage = "https://github.com/ruma/ruma-events"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-events"
readme = "README.md"
repository = "https://github.com/ruma/ruma-events"
version = "0.13.0"
edition = "2018"

[dependencies]
ruma-identifiers = "0.14.0"
ruma-events-macros = "0.1.0"
serde_json = "1.0.40"

[dependencies.js_int]
version = "0.1.1"
features = ["serde"]

[dependencies.serde]
version = "1.0.97"
features = ["derive"]
