[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix client-server API."
documentation = "https://docs.rs/ruma-client-api"
homepage = "https://github.com/ruma/ruma-client-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
version = "0.4.0"
edition = "2018"

[dependencies]
js_int = { version = "0.1.2", features = ["serde"] }
ruma-api = "0.11.2"
ruma-events = "0.15.1"
ruma-identifiers = "0.14.0"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
url = { version = "2.1.0", features = ["serde"] }
