[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "A Matrix client library."
documentation = "https://docs.rs/ruma-client"
edition = "2018"
homepage = "https://github.com/ruma/ruma-client"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client"
version = "0.3.0-beta.2"

[dependencies]
futures-core = "0.3.1"
futures-util = "0.3.1"
http = "0.2.0"
hyper = "0.13.1"
hyper-tls = { version = "0.4.0", optional = true }
ruma-api = "0.12.0"
ruma-client-api = "0.5.0"
ruma-events = "0.15.1"
ruma-identifiers = "0.14.1"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.44"
serde_urlencoded = "0.6.1"
url = "2.1.0"

[dev-dependencies]
tokio = { version = "0.2.4", features = ["macros"] }

[features]
default = ["tls"]
tls = ["hyper-tls"]
