[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
name = "ruma-api-macros"
version = "0.1.0"

[dependencies]
quote = "0.3.15"
synom = "0.11.3"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
rev = "fed04dfb58e19b408322d4e5ca7474871e848a35"

[dependencies.ruma-api]
git = "https://github.com/ruma/ruma-api"
rev = "3635fe51ac31b9ff899c70a0d1218caa8cf6a8dc"

[dependencies.syn]
features = ["full"]
version = "0.11.11"

[dev-dependencies]
futures = "0.1.13"
serde = "1.0.4"
serde_derive = "1.0.4"
serde_json = "1.0.2"

[lib]
doctest = false
proc-macro = true
