[package]
authors = [
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Jonas Platte <jplatte@posteo.de>",
]
categories = ["api-bindings", "web-programming"]
description = "A Matrix client library."
documentation = "https://docs.rs/ruma-client"
edition = "2018"
homepage = "https://github.com/ruma/ruma-client"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client"
version = "0.3.0"

[dependencies]
futures-core = "0.3.4"
futures-util = "0.3.4"
http = "0.2.1"
hyper = "0.13.4"
hyper-tls = { version = "0.4.1", optional = true }
ruma-api = "0.15.0"
ruma-client-api = "0.7.1"
ruma-events = "0.18.0"
ruma-identifiers = "0.14.1"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
serde_urlencoded = "0.6.1"
url = "2.1.1"

[dev-dependencies]
tokio = { version = "0.2.16", features = ["macros"] }

[features]
default = ["tls"]
tls = ["hyper-tls"]
