[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A Matrix client library."
documentation = "https://docs.rs/ruma-client"
homepage = "https://github.com/ruma/ruma-client"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client"
version = "0.1.0"

[dependencies]
futures = "0.1.14"
http = "0.1"
hyper = "0.12"
ruma-api = "0.4.0"
ruma-client-api = "0.1.0"
ruma-identifiers = "0.11.0"
serde_json = "1.0.2"
serde_urlencoded = "0.5.1"
url = "1.5.1"

[dependencies.hyper-tls]
optional = true
version = "0.3.0"

[dependencies.native-tls]
optional = true
version = "0.2.1"

[dev-dependencies]
futures-await = { git = 'https://github.com/alexcrichton/futures-await' }
ruma-events = "0.9.0"

[features]
default = ["tls"]
tls = ["hyper-tls", "native-tls"]
