[package]
authors = [
  "Jimmy Cuadra <jimmy@jimmycuadra.com>",
  "Jonas Platte <jplatte@posteo.de>",
]
categories = ["api-bindings", "web-programming"]
description = "An abstraction for Matrix API endpoints."
documentation = "https://docs.rs/ruma-api"
homepage = "https://github.com/ruma/ruma-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api"
version = "0.16.0-rc.3"
edition = "2018"

[dependencies]
http = "0.2.1"
percent-encoding = "2.1.0"
ruma-api-macros = { version = "=0.16.0-rc.3", path = "ruma-api-macros" }
ruma-identifiers = "0.16.0"
ruma-serde = "0.1.3"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
strum = "0.18.0"

[dev-dependencies]
ruma-events = "0.21.0-beta.1"

[workspace]
members = [
  "ruma-api-macros",
]
