[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix client-server API."
documentation = "https://docs.rs/ruma-client-api"
homepage = "https://github.com/ruma/ruma-client-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
version = "0.6.0"
edition = "2018"

[dependencies]
http = "0.2.0"
js_int = { version = "0.1.3", features = ["serde"] }
ruma-api = "0.15.0-dev.1"
ruma-events = "0.17.0"
ruma-identifiers = "0.14.1"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
strum = { version = "0.18.0", features = ["derive"] }
url = { version = "2.1.1", features = ["serde"] }
