[workspace]
members = ["crates/*", "examples/*", "xtask"]
# Only compile / check / document the public crates by default
default-members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
assert_matches = "1.5.0"
assign = "1.1.1"
base64 = "0.21.0"
criterion = "0.4.0"
http = "0.2.8"
js_int = "0.2.2"
maplit = "1.0.2"
serde = { version = "1.0.147", features = ["derive"] }
serde_html_form = "0.2.0"
serde_json = "1.0.87"
thiserror = "1.0.37"
tracing = { version = "0.1.37", default-features = false, features = ["std"] }

[profile.dev]
# Speeds up test times by more than 10% in a simple test
# Set to 1 or 2 if you want to use a debugger in this workspace
debug = 0

[profile.dev.package]
# Also speeds up test times a little bit
quote = { opt-level = 2 }
