[package]
name = "state-res"
version = "0.1.0"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
edition = "2018"
categories = ["api-bindings", "web-programming"]
description = "An abstraction for Matrix state resolution."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "state resolution", "ruma"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ruma/state-res"

[dependencies]
itertools = "0.10.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
maplit = "1.0.2"
thiserror = "1.0.22"
log = "0.4.11"

[features]
unstable-pre-spec = ["ruma/unstable-pre-spec"]

[dependencies.ruma]
git = "https://github.com/ruma/ruma"
rev = "d883debe072086efffd4255dcca0a1a0d6fcd9ce"
features = ["events", "signatures"]

[dev-dependencies]
criterion = "0.3.3"
rand = "0.7.3"
tracing-subscriber = "0.2.15"

[[bench]]
name = "state_res_bench"
harness = false
