[package]
name = "state-res"
version = "0.1.0"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
edition = "2018"
categories = ["api-bindings", "web-programming"]
description = "An abstraction for Matrix state resolution."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "state resolution", "ruma"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ruma/state-res"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
itertools = "0.9.0"
js_int = "0.1.9"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
tracing = "0.1.19"
maplit = "1.0.2"
thiserror = "1.0.20"
tracing-subscriber = "0.2.11"

[dependencies.ruma]
path = "../ruma/ruma"
features = ["client-api", "federation-api", "appservice-api"]

#[dependencies.ruma]
#git = "https://github.com/ruma/ruma"
#rev = "aff914050eb297bd82b8aafb12158c88a9e480e1"
#features = ["client-api", "federation-api", "appservice-api"]

[features]
unstable-pre-spec = ["ruma/unstable-pre-spec"]

[dev-dependencies]
criterion = "0.3.3"
rand = "0.7.3"

[[bench]]
name = "state_res_bench"
harness = false

