[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Core API types for Matrix."
documentation = "https://docs.rs/ruma-api"
homepage = "https://github.com/ruma/ruma-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api"
version = "0.3.0"

[dependencies]
futures = "0.1.14"
hyper = "0.11"
serde_json = "1.0.2"

[dev-dependencies]
ruma-identifiers = "0.11"
serde = "1.0"
serde_derive = "1.0"
