[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings"]
description = "Resource identifiers for Matrix."
documentation = "https://docs.rs/ruma-identifiers"
homepage = "https://github.com/ruma/ruma-identifiers"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-identifiers"
readme = "README.md"
repository = "https://github.com/ruma/ruma-identifiers"
version = "0.14.0"
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
rand = "0.7.0"
regex = "1.2.0"
serde = "1.0.97"
url = "2.0.0"

[dependencies.diesel]
optional = true
version = "1.4.2"

[dev-dependencies]
serde_json = "1.0.40"
