[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings"]
description = "Serializable types for the events in the Matrix specification."
documentation = "https://docs.rs/ruma-events"
homepage = "https://github.com/ruma/ruma-events"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-events"
readme = "README.md"
repository = "https://github.com/ruma/ruma-events"
version = "0.21.3"
edition = "2018"

[dependencies]
js_int = { version = "0.1.5", features = ["serde"] }
ruma-common = "0.1.1"
ruma-events-macros = { path = "ruma-events-macros", version = "=0.21.3" }
ruma-identifiers = "0.16.1"
ruma-serde = "0.2.1"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = { version = "1.0.53", features = ["raw_value"] }
strum = { version = "0.18.0", features = ["derive"] }

[dev-dependencies]
maplit = "1.0.2"
matches = "0.1.8"
ruma-identifiers = { version = "0.16.1", features = ["rand"] }

[workspace]
members = [
    "ruma-events-macros",
]
