[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Digital signatures according to the Matrix specification."
documentation = "https://docs.rs/ruma-signatures"
homepage = "https://github.com/ruma/ruma-signatures"
keywords = ["matrix", "chat", "messaging", "ruma", "cryptography"]
license = "MIT"
name = "ruma-signatures"
readme = "README.md"
repository = "https://github.com/ruma/ruma-signatures"
version = "0.4.0"

[dependencies]
base64 = "0.5.0"
lazy_static = "0.2.8"
ring = "0.9.4"
serde = "1.0"
serde_json = "1.0"
untrusted = "0.5"
url = "1.4"

[dev-dependencies]
serde_derive = "1.0"
