[package]
name = "hello_isahc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ruma = { version = "0.6.3", path = "../../crates/ruma", features = ["client-api-c", "client-ext-client-api", "client-isahc", "rand"] }

anyhow = "1.0.37"
isahc = "1.3.1"
tokio = { version = "1.0.1", features = ["macros", "rt"] }
