[package]
categories = ["api-bindings", "web-programming"]
description = "Deprecated: crate merged into ruma-macros"
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-serde-macros"
repository = "https://github.com/ruma/ruma"
version = "0.6.1"
edition = "2018"

[badges]
maintenance = { status = "deprecated" }

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.0.0"
proc-macro2 = "1.0.24"
quote = "1.0.8"
syn = { version = "1.0.55", features = ["full"] }
