[package]
authors = [
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Jonas Platte <jplatte@posteo.de>",
    "Isaiah Inuwa <isaiah.inuwa@gmail.com>",
]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix client-server API."
documentation = "https://docs.rs/ruma-client-api"
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
version = "0.9.0"
edition = "2018"

[dependencies]
http = "0.2.1"
js_int = { version = "0.1.7", features = ["serde"] }
ruma-api = { version = "0.16.1", path = "../ruma-api" }
ruma-common = { version = "0.2.0", path = "../ruma-common" }
ruma-events = { version = "0.21.3", path = "../ruma-events" }
ruma-identifiers = { version = "0.17.1", path = "../ruma-identifiers" }
ruma-serde = { version = "0.2.2", path = "../ruma-serde" }
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.55"
strum = { version = "0.18.0", features = ["derive"] }

[dev-dependencies]
maplit = "1.0.2"
matches = "0.1.8"

[features]
unstable-pre-spec = []
unstable-synapse-quirks = []
