[package]
authors = ["Jonas Platte <jplatte@posteo.de>"]
description = "Procedural macros for creating Matrix identifiers."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-identifiers-macros"
repository = "https://github.com/ruma/ruma"
version = "0.19.0"
edition = "2018"

[dependencies]
ruma-identifiers-validation = { version = "0.3.0", path = "../identifiers-validation", default-features = false }
quote = "1.0.8"
proc-macro2 = "1.0.24"
syn = "1.0.55"

[lib]
proc-macro = true
