[package]
name = "serde_urlencoded"
version = "0.6.1"
authors = ["Anthony Ramine <n.oxyde@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/nox/serde_urlencoded"
documentation = "https://docs.rs/serde_urlencoded"
description = "`x-www-form-urlencoded` meets Serde"
categories = ["encoding", "web-programming"]
keywords = ["serde", "serialization", "urlencoded"]
exclude = ["/.travis.yml", "/bors.toml"]
edition = "2018"

[badges]
travis-ci = {repository = "nox/serde_urlencoded"}

[lib]
test = false

[dependencies]
dtoa = "0.4.5"
itoa = "0.4.5"
serde = { version = "1.0.106", features = ["derive"] }
url = "2.1.1"
