[package]
authors = ["Jonas Platte <jplatte@posteo.de>"]
description = "Procedural macros for creating Matrix identifiers."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-identifiers-macros"
repository = "https://github.com/ruma/ruma"
version = "0.19.1"
edition = "2018"

[dependencies]
quote = "1.0.8"
ruma-identifiers-validation = { version = "0.4.0", path = "../ruma-identifiers-validation", default-features = false }
syn = "1.0.55"

[lib]
proc-macro = true
