[package]
name = "ruma-state-res"
categories = ["api-bindings", "web-programming"]
keywords = ["matrix", "chat", "ruma"]
description = "An abstraction for Matrix state resolution."
homepage = "https://www.ruma.io/"
repository = "https://github.com/ruma/ruma"
readme = "README.md"
license = "MIT"
version = "0.9.0"
edition = "2021"
rust-version = "1.64"

[package.metadata.docs.rs]
all-features = true

[features]
unstable-exhaustive-types = []

[dependencies]
itertools = "0.10.0"
js_int = { workspace = true }
ruma-common = { workspace = true, features = ["events"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# dev-dependencies can't be optional, so this is a regular dependency
criterion = { workspace = true, optional = true }

[dev-dependencies]
maplit = { workspace = true }
rand = "0.8.3"
ruma-common = { workspace = true, features = ["unstable-pdu"] }
tracing-subscriber = "0.3.16"

[[bench]]
name = "state_res_bench"
harness = false
required-features = ["criterion"]
