[package]
name = "ruma-state-res"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
categories = ["api-bindings", "web-programming"]
keywords = ["matrix", "chat", "state resolution", "ruma"]
description = "An abstraction for Matrix state resolution."
homepage = "https://www.ruma.io/"
repository = "https://github.com/ruma/ruma"
readme = "README.md"
license = "MIT"
version = "0.1.0"
edition = "2018"

[features]
unstable-pre-spec = ["ruma-events/unstable-pre-spec"]

[dependencies]
itertools = "0.10.0"
js_int = "0.2.0"
maplit = "1.0.2"
ruma-common = { version = "0.5.0", path = "../ruma-common" }
ruma-events = { version = "=0.22.0-alpha.3", path = "../ruma-events" }
ruma-identifiers = { version = "0.19.0", path = "../ruma-identifiers" }
ruma-serde = { version = "0.4.0", path = "../ruma-serde" }
ruma-signatures = { version = "0.7.0", path = "../ruma-signatures" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
thiserror = "1.0.22"
tracing = "0.1.26"

[dev-dependencies]
criterion = "0.3.3"
rand = "0.8.3"
tracing-subscriber = "0.2.15"

[[bench]]
name = "state_res_bench"
harness = false
