[package]
name = "ruma-state-res"
categories = ["api-bindings", "web-programming"]
keywords = ["matrix", "chat", "ruma"]
description = "An abstraction for Matrix state resolution."
homepage = "https://www.ruma.io/"
repository = "https://github.com/ruma/ruma"
readme = "README.md"
license = "MIT"
version = "0.6.0"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
compat = []
unstable-exhaustive-types = []

# Private, only used in test / benchmarking code
__ci = ["ruma-common/unstable-pre-spec"]

[dependencies]
itertools = "0.10.0"
js_int = "0.2.0"
ruma-common = { version = "0.8.0", path = "../ruma-common", features = ["events"] }
ruma-serde = { version = "0.6.0", path = "../ruma-serde" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
thiserror = "1.0.26"
tracing = "0.1.26"

[dev-dependencies]
criterion = "0.3.3"
maplit = "1.0.2"
rand = "0.8.3"
ruma-common = { version = "0.8.0", path = "../ruma-common", features = ["unstable-pdu"] }
tracing-subscriber = "0.3.3"

[[bench]]
name = "state_res_bench"
harness = false
