[package]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix server-server API."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-federation-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma"
version = "0.5.0"
edition = "2021"
rust-version = "1.59"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
compat = []
client = []
server = []
unstable-exhaustive-types = []
unstable-pre-spec = []
unstable-msc2448 = []
unstable-msc3618 = []
unstable-msc3723 = []

[dependencies]
js_int = { version = "0.2.0", features = ["serde"] }
ruma-common = { version = "0.9.2", path = "../ruma-common", features = ["api", "events"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"

[dev-dependencies]
assert_matches = "1.5.0"
http = "0.2.2"
