name: Rust 1.55

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  all_features:
    name: Check All Features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id_storage: ["", "Arc"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install rust 1.55 toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.55"
      # Used to compile xtask
      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          # A stable compiler update should automatically not reuse old caches.
          # Add the MSRV as a stable cache key too so bumping it also gets us a
          # fresh cache.
          sharedKey: msrv1.55
      - name: Run checks
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: --cfg='ruma_identifiers_storage="${{ matrix.id_storage }}"'
        with:
          command: run
          args: -p xtask --no-default-features ci msrv-all

  client:
    name: Check Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install rust 1.55 toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.55"
      # Used to compile xtask
      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          # A stable compiler update should automatically not reuse old caches.
          # Add the MSRV as a stable cache key too so bumping it also gets us a
          # fresh cache.
          sharedKey: msrv1.55
      - name: Run checks
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p xtask --no-default-features ci msrv-client

  ruma:
    name: Check Ruma
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install rust 1.55 toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.55"
      # Used to compile xtask
      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          # A stable compiler update should automatically not reuse old caches.
          # Add the MSRV as a stable cache key too so bumping it also gets us a
          # fresh cache.
          sharedKey: msrv1.55
      - name: Run checks
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p xtask --no-default-features ci msrv-ruma
