name: Rust Nightly

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id_storage: ["", "Arc"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Run checks
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: --cfg='ruma_identifiers_storage="${{ matrix.id_storage }}"'
        with:
          command: run
          args: -p xtask --no-default-features ci fmt

  check_full:
    name: Check Full Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Run checks
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p xtask --no-default-features ci nightly-full

  clippy_default:
    name: Clippy Default Features
    runs-on: ubuntu-latest
    needs: check_full
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Run lints
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p xtask --no-default-features ci clippy-default

  clippy_all:
    name: Clippy All Features
    runs-on: ubuntu-latest
    needs: check_full
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Run lints
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p xtask --no-default-features ci clippy-all
